# Generated by Django 4.2.7 on 2023-11-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='ticket_price',
            field=models.FloatField(default=0),
        ),
    ]
