# Generated by Django 4.2.7 on 2023-11-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventmodel_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='eventmodel',
            unique_together={('event_date', 'event_time', 'city')},
        ),
    ]
