# Generated by Django 4.2.7 on 2023-11-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventmodel_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'ordering': ['event_date']},
        ),
    ]
