# Generated by Django 4.2.7 on 2023-12-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventmodel_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='eventmodel',
            unique_together={('event_date', 'event_time', 'venue')},
        ),
    ]
