# Generated by Django 4.2.7 on 2023-12-01 10:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventmodel_unique_together_eventmodel_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='event_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
